export const FETCH_POKEMONS_SUCCESS = 'FETCH_POKEMONS_SUCCESS'

export const EDIT_FAVORITE_POKEMON_SUCCESS = 'EDIT_FAVORITE_POKEMON_SUCCESS'

export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'

export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'

export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS'

export const CHANGE_ACTIVE_USER = 'CHANGE_ACTIVE_USER'